### PR TITLE
Lift the code up to modern JS and ESM

### PR DESCRIPTION
**Pull request by Pomax**
Monster PR time!  ...what changed?
- it's now an ES module that will only inject a global `DragDropTouch` object when not loaded with `?autoload`.
  - on that note, that query argument will immediately enable the polyfill for the entire page
  - if it's _not_ there, a `window.DragDropTouch` object gets created, which as a single function, `DragDropTouch.enable()` that has the same signature as the DragDropTouch class constructor.
- as an ES module, you can now also use `import { enableDragDropTouch} from "....";` and then bootstrap a more specific DragDropTouch instance.
- related, all the constructor options have been added to the README.md
- I added an esbuild task that bundles the `ts` files into `drap-drop-touch.esm.js` and `drag-drop-touch.esm.min.js`, with an explicit `esm` infix to contrast it to the current non-esm version
- I added `prettier` as code formatter mostly because having to even think about code formatting should be a thing of the past =D
- I added `playwright` integration testing so that we can confirm that touch events do what we expect. These tests are currently non-exhaustive, but it's a start and should be pretty easy to build out
  - related, the demo now has a touch simulator because that's necessary to run tests
  - also related, there is now a `server.js` with a normal mode that hosts the demo content when run (e.g. for localhost work) or runs in a special test-only mode so that playwright can do its job.
  - related the third, I've updated the demo to stick to purely HTML without any specific framework (so there's no banner popups about an expired trial license for wijmo)
- I tried to change the library itself as little as possible, but I did do some minor work on it:
  - strings use either `"`" or backticks
  - all functions have JSDoc headers, although I've not finished (or started?) writing the docs for each of them
  - I've rewritten the `copyComputedStyles` function to take advantage of `for...of`
  - I've cleaned up some of the typing so that VSCode doesn't complain about anything
  - I've added "scroll hot regions" so that dragging an item around is allowed to scroll the page, but only when the user drags into the (by default)  10% top, right, bottom, and left edge regions. This allows folks to drag and drop elements into drop zones that are off-screen (this does not currently have a test, but would be a great next test to write)

Things I'd like to do after merging:

- [ ] release the library to npm, because it's not on there, but it would be mighty useful if it were, and
- [ ] release the library to cdnjs, because telling people to use the github.io URL as CDN url is "technically" fine but github.io doesn't like hotlinking and it's entirely possible that you can't import it that way anymore (I've not tested that). With over 450 stars it should be trivial to get https://cdnjs.com/ to accept this library (I've done this before for https://cdnjs.com/libraries/graphics-element so I'm pretty confident we can do this here, too)

### CODE REVIEW

**Comment by Pomax** [comment]
@Bernardo-Castilho this is basically a placeholder PR with all the changes, and now that I've figured out how to do touch event based integration testing I'll be "finishing it up" by writing a bunch of tests, In terms of all the changes, the easiest _for me_ would be just this PR, but the easiest _for you_ would probably be individual PRs that add the changes incrementally. Let me know which one you'd prefer.

**Comment by Pomax** [comment]
(note that comparing this PR might look scary, but if you turn on "hide whitespace" things become a lot easier:

image

**Comment by Bernardo-Castilho** [comment]
Whatever is easier for you is ok by me. 

I really appreciate your work on this!

**Comment by Pomax** [comment]
Single PR it is =)

I've added some tests (all of two, wow! but it's a start) that confirm drag-and-drop works as intended, so this is probably ready for review. I've updated the original comment to go over what I did, if any of that feels objectionable, let me know. And of course if you have any questions about specific lines of code, drop in a PR comment at that line =)

**Review by Bernardo-Castilho — COMMENTED** [review]
Looks good to me!

**Comment by Pomax** [comment]
Awesome, I'll add a workflow action so PRs automatically get tested, and get this on npmjs and cdnjs.

**Pull request merged**
